server.port=${PORT:8080}
spring.application.name=gomoku

spring.sql.init.mode=never

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.hikari.connection-timeout=10000

spring.main.lazy-initialization=false
